"""empty message

Revision ID: 1201b727933f
Revises: c7792159489b
Create Date: 2020-10-13 20:34:41.414513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1201b727933f'
down_revision = 'c7792159489b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
