"""empty message

Revision ID: 2ffbe2a132f0
Revises: 60a8cf59c8e0
Create Date: 2020-10-13 22:06:35.176941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ffbe2a132f0'
down_revision = '60a8cf59c8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('StartTime', sa.DateTime(), nullable=False))
    op.add_column('Show', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('Show', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('Show', 'id')
    op.drop_column('Show', 'StartTime')
    # ### end Alembic commands ###
