"""empty message

Revision ID: dc1b4085b664
Revises: 621fec962ea3
Create Date: 2020-10-14 10:11:10.564032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1b4085b664'
down_revision = '621fec962ea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_venue')
    # ### end Alembic commands ###
