"""empty message

Revision ID: f9909b6e6147
Revises: 1201b727933f
Create Date: 2020-10-13 21:42:10.308063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9909b6e6147'
down_revision = '1201b727933f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('StartTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'StartTime')
    # ### end Alembic commands ###
